name: ftp-with-lfs
description: Load everything with LFS over FTP
inputs:
  ftp-user:
    description: "Your FTP user"
    required: true
  ftp-password:
    description: "Your FTP password"
    required: true
  ftp-domain:
    description: "Your FTP domain"
    required: true
  cache:
    description: "Enable caching for your LFS files"
    default: "true"
    required: false

runs:
  using: composite
  steps:
    - name: Setup path for bin
      run: echo "${{ github.action_path }}/bin" >> $GITHUB_PATH
      shell: bash
        
    - name: Install curlftpfs and libfuse2
      shell: bash
      run: |
        sudo dpkg -i ${{ github.action_path }}/packages/libfuse2_2.9.9-5ubuntu3_amd64.deb
        sudo dpkg -i ${{ github.action_path }}/packages/curlftpfs_0.9.2-9build1_amd64.deb

    - name: Mount folder
      shell: bash
      run: |
        mkdir $HOME/lfs
        curlftpfs -o user='${{ inputs.ftp-user }}:${{ inputs.ftp-password }}' ftp://${{ inputs.ftp-domain }}/ $HOME/lfs -v

    - name: Config LFS provider
      shell: bash
      run: |
        git config --add lfs.customtransfer.lfs-folder.path lfs-folderstore
        git config --add lfs.customtransfer.lfs-folder.args "$HOME/lfs"
        git config --add lfs.standalonetransferagent lfs-folder

    - name: Create LFS file list
      if: ${{ inputs.cache == 'true' }}
      shell: bash
      run: git lfs ls-files --long | cut -d ' ' -f1 | sort > .lfs-assets-id

    - name: LFS Cache
      if: ${{ inputs.cache == 'true' }}
      uses: actions/cache@v3
      with:
        path: .git/lfs/objects
        key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
        restore-keys: |
          ${{ runner.os }}-lfs-

    - name: Git LFS Pull
      shell: bash
      run: git lfs pull
